title: RBE Solutions database
short_title: RBE Solutions database
description: Designs, technologies and other solutions to be used in projects trying to transition to RBE
baseurl: /
permalink: "/:path/"
defaults:
  - scope:
      path: ""
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: part
collections:
  people:
    output: true
    permalink: "/about/:path/"
  posts:
    output: true
  projects:
    output: true
    permalink: "/projects/:path/"
# tag_page_layout: tag_page
# tag_page_dir: tag
jekyll-archives:
  enabled: all
  layout: "archive"
plugins:
  - jekyll-menus
  - jekyll-feed
  - jekyll-archives
  - jekyll-toc
  - jekyll-sitemap
 
theme: jekyll-theme-so-simple
#theme: jekyll-theme-architect